
name: ${{ parameters.VersionNumberMajor }}.${{ parameters.VersionNumberMinor }}.$(Rev:.r)
#name:  $(GitVersion.NuGetVersion)
#name: $(GitVersion.SemVer)

parameters:
- name: BuildConfiguration
  displayName: Release or Debug
  type: string
  default: Release
  values:
  - Release
  - Debug

- name: VersionNumberMajor
  displayName: 'Version Number : Major'
  type: string
  default: '0'  

- name: VersionNumberMinor
  displayName: 'Version Number : Minor'
  type: string
  default: '1'  
  

resources:
- repo: self
  fetchDepth: 30

variables:
  Build.Platform: 'Any CPU'
  Build.PlatformX64: 'x64'  
  DotNetCore.Version: '2.2.207'  
  Parameters.solution: '**\*.sln'
  Parameters.feedRestore: 'dct-pkg'

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      name: DCT
      demands:
      - IsBuildServer
      - ServiceFabricSDK

    steps:
    - powershell: |
           $Filter = "ApplicationParameters";
           $ApplicationParametersFolder = Get-ChildItem -Directory -recurse   | Where {$_.Name.ToLower() -eq $Filter.ToLower() };
           Copy-Item "$($ApplicationParametersFolder.FullName)\Cloud.xml" "$($ApplicationParametersFolder.FullName)\Local.1Node.xml" -Force;
           Copy-Item "$($ApplicationParametersFolder.FullName)\Cloud.xml" "$($ApplicationParametersFolder.FullName)\Local.5Node.xml" -Force;
 
      workingDirectory: '$(build.sourcesdirectory)\src'
      displayName: 'Generate Fake Application Parameters Node Config Files'

    - task: DotNetCoreInstaller@0
      displayName: 'Use .NET Core sdk $(DotNetCore.Version)'
      inputs:
        version: $(DotNetCore.Version)
    
    - task: VisualStudioTestPlatformInstaller@1
      displayName: 'Visual Studio Test Platform Installer'
      inputs:
        versionSelector: latestStable
    
    - task: NuGetToolInstaller@0
      displayName: 'Use NuGet >=5.3.1'
      enabled: true
      inputs:
        versionSpec: '>=5.3.1'

    - task: UseGitVersion@5
      enabled: false
      displayName: use Git Version to generate build number
      inputs:
        versionSpec: '5.x'
        
    # Generate the report using ReportGenerator (https://github.com/danielpalme/ReportGenerator)
    # First install the tool on the machine, then run it
    - script: |
            dotnet tool update dotnet-reportgenerator-globaltool --version 4.3.6  
      displayName: Install/update dotnet-reportgenerator-globaltool
      continueOnError: true  
      enabled: false

    #********************************************************************************
    # Nuget Restore and Build
    #********************************************************************************   
    - task: DotNetCoreCLI@2
      enabled: true
      displayName: 'dotnet restore'
      inputs:
        command: restore
        projects: '**\*.csproj'
        vstsFeed: 'dct-pkg'
    #    noCache: true
    
    - task: NuGetCommand@2
      displayName: 'NuGet restore'
      inputs:
        restoreSolution: '**/*.sln'
        vstsFeed: 'dct-pkg'
    #    noCache: true
    
    - task: MSBuild@1
      enabled: true
      displayName: 'Build solution **/*.sln'
      inputs:
        msbuildVersion: 16.0
        msbuildArchitecture: x64
        platform: '$(Build.Platform)'
        configuration: '${{ parameters.BuildConfiguration }}'
        msbuildArguments: '-p:version=$(Build.BuildNumber) -p:FileVersion=$(Build.BuildNumber) -p:SkipInvalidConfigurations=true'
        clean: true
        maximumCpuCount: true
        logProjectEvents: true
        createLogFile: true
    
    - task: MSBuild@1
      enabled: true
      displayName: 'Build and Package - Service Fabric Config'
      inputs:
        solution: '**\*.sfproj'
        msbuildArchitecture: x64
        platform: '$(Build.PlatformX64)'
        configuration: '${{ parameters.BuildConfiguration }}'
        msbuildArguments: '/t:Package /p:PackageLocation=$(build.artifactstagingdirectory)\ServiceFabric\ApplicationPackage  /p:version=$(Build.BuildNumber) /p:FileVersion=$(Build.BuildNumber) -p:SkipInvalidConfigurations=true'
        clean: false
        maximumCpuCount: true
        logProjectEvents: true
        createLogFile: true
            
    #********************************************************************************
    # Copy and Package files into Artifact Directory
    #******************************************************************************** 
    - task: DeleteFiles@1
      displayName: 'Delete Symbols files from $(build.artifactstagingdirectory)\ServiceFabric\ApplicationPackage '
      inputs:
        SourceFolder: '$(build.artifactstagingdirectory)\ServiceFabric\ApplicationPackage'
        Contents: '**\*.pdb'
    
    - task: CopyFiles@2
      displayName: 'Copy Nuget Interface Packages Files - Artifact NugetInterface Directory'
      inputs:
        SourceFolder: '$(build.sourcesdirectory)\src'
        Contents: |
         **\*${{ parameters.BuildConfiguration }}*\*Interface.nupkg
         !**\packages\**
         !**\bin\x64\**
        TargetFolder: '$(build.artifactstagingdirectory)\Nuget\Interface'
        CleanTargetFolder: true
        flattenFolders: true
    
    - task: CopyFiles@2
      displayName: 'Copy NugetPackages Files - Artifact NugetPackages Directory'
      inputs:
        SourceFolder: '$(build.sourcesdirectory)\src'
        Contents: |
         **\*${{ parameters.BuildConfiguration }}*\*.nupkg
         !**\packages\**
         !**\bin\x64\**
        TargetFolder: '$(build.artifactstagingdirectory)\Nuget\Packages'
        CleanTargetFolder: true
        flattenFolders: true
            
    - task: CopyFiles@2
      displayName: 'Copy Database Files - Artifact Databases Directory'
      inputs:
        SourceFolder: '$(build.sourcesdirectory)'
        Contents: '**\*.dacpac'
        TargetFolder: '$(build.artifactstagingdirectory)\Databases'
        CleanTargetFolder: true
        flattenFolders: true
    
    - task: CopyFiles@2
      displayName: 'Copy Files - $(build.artifactstagingdirectory)\ServiceFabric\PublishProfiles'
      inputs:
        SourceFolder: '$(build.sourcesdirectory)\src'
        Contents: '**\PublishProfiles\Cloud.xml'
        TargetFolder: '$(build.artifactstagingdirectory)\ServiceFabric\PublishProfiles'
        CleanTargetFolder: true
        flattenFolders: true
    
    - task: CopyFiles@2
      displayName: 'Copy Files - $(build.artifactstagingdirectory)\ServiceFabric\ApplicationParameters'
      inputs:
        SourceFolder: '$(build.sourcesdirectory)\src'
        Contents: '**\ApplicationParameters\*.xml'
        TargetFolder: '$(build.artifactstagingdirectory)\ServiceFabric\ApplicationParameters'
        CleanTargetFolder: true
        flattenFolders: true
    
    - task: ServiceFabricUpdateManifests@2
      displayName: 'Update Service Fabric Manifests (Manifest versions)'
      inputs:
        applicationPackagePath: '$(build.artifactstagingdirectory)\ServiceFabric\ApplicationPackage '
        versionBehavior: Replace
      enabled: true

    #********************************************************************************
    # Count Artifact Files to decide what to Publish
    #********************************************************************************    
    - task: PowerShell@2
      enabled: true
      displayName: 'Check What to Publish'
      continueOnError: true  
      inputs:
        targetType: 'inline'
        script: |
                  Write-Host "##vso[task.setvariable variable=PublishArtifact_ServiceFabric]$(Test-Path '$(build.artifactstagingdirectory)\ServiceFabric' -PathType Any)";
                  Write-Host "##vso[task.setvariable variable=PublishArtifact_NugetPackages]$(Test-Path '$(build.artifactstagingdirectory)\Nuget' -PathType Any)";
                  Write-Host "##vso[task.setvariable variable=PublishArtifact_Databases]$(Test-Path '$(build.artifactstagingdirectory)\Databases' -PathType Any)";
    
    #********************************************************************************   
    # Run Unit Tests
    #********************************************************************************
    - task: DotNetCoreCLI@2
      enabled: true
      displayName: 'Run xUnit Test - Core Framework'
      inputs:
        command: test
        projects: 'src/**/*Tests.csproj'
        arguments: '--configuration ${{ parameters.BuildConfiguration }} --collect "Code coverage"'
        
    - task: VSTest@2
      enabled: false
      displayName: 'VsTest - testAssemblies'
      inputs:
        testAssemblyVer2: |
         **\ESFA.DC.ESF.R2.*tests.dll
         !**\*Database.Tests*\**
         !**\packages\**
         !**\obj\**
        configuration: '${{ parameters.BuildConfiguration }}'

    #********************************************************************************
    # Generate Code Coverage Report and Publish
    #********************************************************************************
 
    ## Generate the report using ReportGenerator (https://github.com/danielpalme/ReportGenerator)
    # First install the tool on the machine, then run it
    - script: |
        dotnet tool install -g dotnet-reportgenerator-globaltool --version 4.3.6  
        reportgenerator -reports:$(Build.SourcesDirectory)/**/*Tests/**/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/CodeCoverage -reporttypes:Cobertura

      displayName: Create Code coverage report
      enabled: false
  
    # Publish the code coverage result (summary and web site)
    # The summary allows to view the coverage percentage in the summary tab
    # The web site allows to view which lines are covered directly in Azure Pipeline
    - task: PublishCodeCoverageResults@1
      displayName: 'Publish Code Coverage'
      enabled: false
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(Build.SourcesDirectory)/CodeCoverage/Cobertura.xml'
        reportDirectory: '$(Build.SourcesDirectory)/CodeCoverage'

    #********************************************************************************
    # Publish Artifacts
    #********************************************************************************    
    - task: PublishSymbols@2
      enabled: false
      displayName: 'Publish symbols path'
      inputs:
        SearchPattern: '**\bin\**\*.pdb'
        PublishSymbols: false
      continueOnError: true
    
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: ServiceFabric'
      condition: and(succeeded(), eq(variables['PublishArtifact_ServiceFabric'], 'True'))
      inputs:
        ArtifactName: ServiceFabric
        PathtoPublish: '$(build.artifactstagingdirectory)\ServiceFabric'
    
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: NugetPackages'
      condition: and(succeeded(), eq(variables['PublishArtifact_NugetPackages'], 'True'))
      inputs:
        ArtifactName: NugetPackages
        PathtoPublish: '$(build.artifactstagingdirectory)\Nuget'
    
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: Databases'
      condition: and(succeeded(), eq(variables['PublishArtifact_Databases'], 'True'))
      inputs:
        ArtifactName: Databases
        PathtoPublish: '$(build.artifactstagingdirectory)\Databases'
    